import os

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
SMS_STORAGE_PATH = os.getenv("SMS_STORAGE_PATH")
PUSHOVER_API_TOKEN = os.getenv("PUSHOVER_API_TOKEN")
PUSHOVER_API_USER_KEY = os.getenv("PUSHOVER_API_USER_KEY")
